version: "3.9"

services:

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    env_file:
      - ./backend/api-gateway/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    depends_on:
      - user-service
      - cart-service
      - item-service
      - payment-service
      - notification-service
      - order-service
    networks:
      - app-network


  user-service:
    build: ./backend/user-service
    container_name: user-service
    env_file:
      - ./backend/user-service/.env
    ports:
      - "5001:5001"
    volumes:
      - ./backend/user-service:/app
      - /app/node_modules
    networks:
      - app-network


  cart-service:
    build: ./backend/cart-service
    container_name: cart-service
    env_file:
      - ./backend/cart-service/.env
    ports:
      - "5002:5002"
    volumes:
      - ./backend/cart-service:/app
      - /app/node_modules
    networks:
      - app-network


  item-service:
    build: ./backend/items-service
    container_name: item-service
    env_file:
      - ./backend/items-service/.env
    ports:
      - "5003:5003"
    volumes:
      - ./backend/items-service:/app
      - /app/node_modules
    networks:
      - app-network


  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    env_file:
      - ./backend/payment-service/.env
    ports:
      - "5004:5004"
    volumes:
      - ./backend/payment-service:/app
      - /app/node_modules
    networks:
      - app-network


  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    env_file:
      - ./backend/notification-service/.env
    ports:
      - "5005:5005"
    volumes:
      - ./backend/notification-service:/app
      - /app/node_modules
    networks:
      - app-network


  order-service:
    build: ./backend/order-service
    container_name: order-service
    env_file:
      - ./backend/order-service/.env
    ports:
      - "5006:5006"
    volumes:
      - ./backend/order-service:/app
      - /app/node_modules
    networks:
      - app-network


  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - app-network


networks:
  app-network:
    driver: bridge